# Configuración del modelo de islas y la base de datos
num_islands: 4
archive_size: 50
migration_interval: 5
migration_rate: 0.1
island_elitism: true
parent_selection_strategy: "weighted" # Opciones: "weighted", "power_law"
parent_selection_lambda: 10.0
exploitation_alpha: 1.0
exploitation_ratio: 0.2